language: php

matrix:
  include:
    - php: 5.6
      dist: xenial
    - php: 7.0
      dist: xenial
    - php: 7.1
      dist: xenial
    - php: 7.2
      dist: xenial
    - php: 7.3
      dist: xenial
    - php: 7.4
      dist: xenial
    - php: 8.0
      dist: bionic
    - php: 8.1.0
      dist: bionic
    - php: nightly
      dist: bionic
  allow_failures:
    - php: nightly

before_install: true

install:
  - phpenv config-rm xdebug.ini
  - eval `ssh-agent -s`
  - travis/setup-secure-shell.sh
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' -a `php -r "echo (int) version_compare(PHP_VERSION, '7.0', '<');"` = "1" ]; then travis/install-php-extensions.sh; fi"
  - travis/setup-composer.sh

script:
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.5' ]; then vendor/bin/phing -f build/build.xml sniff; fi"
  - travis/run-phpunit.sh
