language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

env:
  global:
    # Defines CODE_COVERAGE_PASSPHRASE which is the passphrase for unlocking
    # the travis/code_coverage_id_rsa RSA private key.
    - secure: "jtQTZKQBnzUlp/jz7NlM6470ZDnLGVAs53sgvIm4tcYqf9TWSXSXjIYvFsrS\nKPR2eyZaAevYysUkIGRFTUXTlG6tC36YngMp9+6FPxASl8mnGXsTbKcm613B\n59vD3242pgIgqhhmgFQ0c8gbvnE8PuF2aS4/hluP3r+AxhWN56E="

before_install: true

install:
  - wget http://ftp.gnu.org/gnu/parallel/parallel-20120522.tar.bz2
  - tar -xvjf parallel*
  - cd parallel*
  - ./configure
  - make
  - sudo make install
  - cd ..
  - eval `ssh-agent -s`
  - travis/setup-secure-shell.sh
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' -a `php -r "echo (int) version_compare(PHP_VERSION, '7.0', '<');"` = "1" ]; then travis/install-php-extensions.sh; fi"
  - travis/setup-composer.sh

script:
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.5' ]; then vendor/bin/phing -f build/build.xml sniff; fi"
  - travis/run-phpunit.sh

after_success:
  - sh -c "if $TRAVIS_SECURE_ENV_VARS; then travis/upload-code-coverage-html.sh; fi"
